#!/usr/bin/env node
/**
 * redT Homes — community map generator (zero dependencies, Node's fs/path only)
 *
 * Reads data/communities.json (name/city/lat/lng/link per community) and
 * data/listings.json (to compute each community's live price range + home
 * count), then regenerates the "Where We're Building" map section between
 * the <!-- MAP:START --> / <!-- MAP:END --> markers in index.html.
 *
 * The map itself is Leaflet + OpenStreetMap tiles (free, no API key). Marker
 * coordinates were geocoded once via OpenStreetMap's Nominatim service and
 * stored in data/communities.json — a few new-construction streets don't
 * resolve to an exact address yet, so those fall back to neighborhood- or
 * town-level coordinates (noted per-entry below where relevant).
 *
 * Run with: node build-map.js
 *
 * To add a new community: add an entry to data/communities.json (needs at
 * least one matching `community` value in data/listings.json to compute a
 * price range), then re-run this script.
 */

const fs = require("fs");
const path = require("path");

const ROOT = __dirname;

function escapeHtml(s) {
  return String(s).replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));
}

function readJSON(p) {
  return JSON.parse(fs.readFileSync(p, "utf8"));
}

function formatPrice(n) {
  return `$${Number(n).toLocaleString("en-US")}`;
}

function main() {
  const communities = readJSON(path.join(ROOT, "data", "communities.json"));
  const listings = readJSON(path.join(ROOT, "data", "listings.json"));

  const markers = communities.map((c) => {
    const inCommunity = listings.filter((l) => l.community === c.name);
    const prices = inCommunity.map((l) => l.price);
    const min = Math.min(...prices);
    const max = Math.max(...prices);
    const priceLabel = min === max ? formatPrice(min) : `${formatPrice(min)} – ${formatPrice(max)}`;
    return {
      name: c.name,
      city: c.city,
      lat: c.lat,
      lng: c.lng,
      link: `/?community=${encodeURIComponent(c.name)}#listings`,
      count: inCommunity.length,
      priceLabel,
    };
  });

  const dataScript = `<script>window.REDT_COMMUNITIES = ${JSON.stringify(markers)};</script>`;

  const section = `<section class="section map-section">
  <div class="listings-head reveal">
    <div>
      <p class="eyebrow">Where We're Building</p>
      <h2>See every community on the map</h2>
    </div>
  </div>
  <div id="community-map" class="community-map reveal"></div>
</section>`;

  const indexPath = path.join(ROOT, "index.html");
  let html = fs.readFileSync(indexPath, "utf8");
  const block = `<!-- MAP:START (auto-generated by build-map.js from data/communities.json + data/listings.json — do not hand-edit) -->\n${section}\n${dataScript}\n    <!-- MAP:END -->`;
  const re = /<!-- MAP:START[\s\S]*?<!-- MAP:END -->/;
  if (!re.test(html)) {
    throw new Error("Could not find MAP:START / MAP:END markers in index.html");
  }
  html = html.replace(re, block);
  fs.writeFileSync(indexPath, html);

  console.log(`Updated homepage community map with ${markers.length} communities.`);
}

main();
